include:
  - project: flywheel-io/scientific-solutions/etc/sse-qa-ci
    ref: ed5c2741e40b85bb00cf28572eab4c34c31dc5d3
    file: ci/default.yml

variables:
  PYTEST_COV_FAIL_UNDER: 90
  DEBUG: "3"  # Set debug mode to print out executed command on qa-ci
  PUBLISH_POETRY: "true"  # Set to true to allow CI to publish package to PYPI
  CACHE_CLEAR: "1"  # Set to true to clear runner cache on gitlab CI
  PYVER: "3.10"


update:profiles:
  stage: update
  rules:
    - if: $UPSTREAM_PROJECT_ID && $UPSTREAM_TAG
      when: always
  script:
    - sed -i "s|PROFILE_VERSION=.*|PROFILE_VERSION=$UPSTREAM_TAG|" Dockerfile
    - /ci/create_mr.sh update-profiles $CI_COMMIT_BRANCH
      title="Update classification profile to $UPSTREAM_TAG"
