repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: poetry run black
        types: [python]
      - id: isort
        name: isort
        language: system
        entry: poetry run isort --profile black .
        types: [python]
      - id: pytest
        name: pytest
        language: system
        # The entrypoint source .env if present which contains env var used by pytest entry
        entry: poetry run bash -euo pipefail -c
          "
          [ ! -f .env ] || . .env;
          pytest tests
            --color=yes
            --cov=$(poetry version | cut -d' ' -f1 | tr - _)
            --cov-fail-under=${COVER:=90}
            --cov-report=term-missing
            --cov-report=xml:coverage.xml
            --junitxml=junit.xml
            -o junit_family=xunit2
          "
        types: [python]
        pass_filenames: false
        verbose: true
