repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: c36806cde04141d414cbd28d50255e93b41e0f9d
    hooks:
      - id: gearcheck
        always_run: true
      - id: poetry_export
      - id: docker_build
      - id: markdownlint
      - id: yamllint
      - id: black
      - id: isort
      - id: pytest
